config/routes.rb
Rails.application.routes.draw do
  # authenticated :user do
  root 'home#index'
  get 'items/home', to: 'home#index'
  get 'items/:id/daily', to: 'items#daily', as: 'daily'
  get 'items/:id/three', to: 'items#three', as: 'three'
  get 'items/:id/week', to: 'items#week', as: 'week'
  get 'items/:id/month', to: 'items#month', as: 'month'
  post 'items/:id/refresh', to: 'items#refresh', as: 'refresh'
  get 'items/search', to: 'home#search', as: 'items_search'
  put 'items/sort_by/:method', to: 'home#sort_by', as: 'items_sort_by'
  put 'items/:id/favourite', to: 'items#favourite', as: 'favourite'
  resources :items, only: %i[show]
  scope :groups do
    get 'most_traded', to: 'home#most_traded', as: 'most_traded'
    get 'top_flips', to: 'home#top_flips', as: 'top_flips'
    get 'barrows_items', to: 'home#barrows_items', as: 'barrows_items'
    get 'zulrah', to: 'home#zulrah', as: 'zulrah'
    get 'potions', to: 'home#potions', as: 'potions'
    get 'ores', to: 'home#ores', as: 'ores'
    get 'food', to: 'home#food', as: 'food'
    get 'free', to: 'home#free', as: 'free'
    get 'favourited', to: 'home#favourited', as: 'favourited'
  end
  # end
  # root 'welcome#index'
  get 'sitemap', to: 'home#sitemap'

  devise_for :users, controllers: { registrations: 'registrations' }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @items = Item.positive_roi
    @items = @items.first(200) # limit it
    @items = sort_items_for_user(current_user, @items)
    @items = ItemDecorator.decorate_collection(@items)
    respond_to do |format|
      format.html
      format.json { render json: @items }
    end
  end

  def search
    name = params.require(:item).permit(:name)[:name]
    @search = true
    @items = Item.search name,
                         fields: [:name],
                         match: :word_start,
                         misspellings: { below: 5 }
    @items = @items.first 200
    @items = sort_items_for_user(current_user, @items)
    @items = ItemDecorator.decorate_collection @items
    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @items }
    end
  end

  def most_traded
    @items = Item.most_traded.to_a
    sort_decorate_render_groups
  end

  def sitemap
  end

  def top_flips
    @items = Item.top_flips.to_a
    @items = ItemDecorator.decorate_collection(@items)
    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @items }
    end
  end

  def sort_decorate_render_groups
    @items = @items.reject { |x| x.roi > 10 }
    @items = @items.reject { |x| x.runescape_id == 13190 } # Old school bond
    @items = sort_items_for_user(current_user, @items)
    @items = ItemDecorator.decorate_collection @items
    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @items }
    end
  end

  def barrows_items
    @items = Item.barrows_items.to_a
    sort_decorate_render_groups
  end

  def food
    @items = Item.food.to_a
    sort_decorate_render_groups
  end

  def zulrah
    @items = Item.zulrah.to_a
    sort_decorate_render_groups
  end

  def potions
    @items = Item.potions.to_a
    sort_decorate_render_groups
  end

  def ores
    @items = Item.ores.to_a
    sort_decorate_render_groups
  end

  def free
    @items = Item.free.to_a
    sort_decorate_render_groups
  end

  def favourited
    return redirect_back fallback_location: root_path, notice: 'You must be signed in!' unless user_signed_in?
    @items = current_user.favourite_items.to_a
    sort_decorate_render_groups
  end

  def sort_by
    return redirect_to root_path, notice: 'You must be signed in to do this!' unless user_signed_in?
    current_user.update(sorting_method: params[:method])
    redirect_back fallback_location: root_path
  end

  def sort_items_for_user(user, items)
    user ||= User.new
    case user.sorting_method
    when 'roi'
      items.sort { |x, y| y.roi <=> x.roi }
    when 'traded'
      items.sort { |x, y| (y.buying_rate + y.selling_rate) <=> (x.buying_rate + x.selling_rate) }
    when 'margin'
      items.sort { |x, y| y.roi * y.margin.abs <=> x.roi * x.margin.abs }
    else # traded_roi
      items.sort { |x, y| y.roi.to_f * (y.buying_rate + y.selling_rate) <=> x.roi.to_f * (x.buying_rate + y.selling_rate) }
    end
  end
end

app/views/home/_preview.html.haml
%a.collection-item.avatar{href: item_path(preview.runescape_id)}
  = image_tag preview.icon_link, class: 'circle', alt: preview.name
  %span.title.white-text
    = preview.name
    %small= preview.recommended_buy
    %small.right.grey-text.text-lighten-2 Traded: #{preview.traded}
  %p{class: "#{preview.margin_style}"}
    .chip{ class: preview.margin_style }
      +
      = preview.margin
    .chip{ class: preview.margin_style }
      = preview.roi

app/views/home/_search.html.haml
-# - unless @q.nil?
-#   .col.s12
-#     .card
-#       .card-content
-#         %span.card-title Search
-#         = search_form_for @q, url: root_path do |f|
-#           = f.search_field :name_cont, placeholder: 'Search...'
.col.s12
  .card
    .card-content
      %span.card-title Search
      = simple_form_for :item, url: items_search_path, method: :get do |f|
        %div{class: "#{'active' unless params[:item].nil?} input-field"}
          = f.input :name, required: false, input_html: {value: params.dig('item', 'name')}

app/views/home/index.html.haml
%ul#group-dropdown.dropdown-content
  %li
    = link_to 'Top flips', top_flips_path
  %li
    = link_to 'Most traded', most_traded_path
  - if user_signed_in?
    %li
      = link_to 'Favourites', favourited_path
  %li.divider
  %li
    = link_to 'Barrows Items', barrows_items_path
  %li
    = link_to 'Zulrah', zulrah_path
  %li
    = link_to 'Potions', potions_path
  %li
    = link_to 'Ores', ores_path
  %li
    = link_to 'Food', food_path
  %li
    = link_to 'Free', free_path
%ul#sort-dropdown.dropdown-content
  %li
    = link_to 'Traded', items_sort_by_path('traded'), method: :put
  %li
    = link_to 'ROI %', items_sort_by_path('roi'), method: :put
  %li
    = link_to 'Margin and ROI', items_sort_by_path('margin'), method: :put
  %li
    = link_to 'Traded and ROI', items_sort_by_path('traded_roi'), method: :put
.row
  = render 'search'
- if Rails.env.production? && false
  .row
    .col.s12
      %script{:async => "", :src => "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
      / Jamflex index
      %ins.adsbygoogle{"data-ad-client" => "ca-pub-4624555430301411", "data-ad-format" => "auto", "data-ad-slot" => "6118776983", :style => "display:block"}
      :javascript
        (adsbygoogle = window.adsbygoogle || []).push({});
.row
  .col.s12
    .card
      .card-content
        %span.card-title
          - if @search
            Search Results
            (
            = @items.count
            )
          - else
            Items
          %span.right
            %a.dropdown-btn.btn.green{href: '#', 'data-activates' => 'group-dropdown'}
              Groups
              %i.material-icons.right arrow_drop_down
            %a.dropdown-btn.btn.green{href: '#', 'data-activates' => 'sort-dropdown'}
              Sort by
              %i.material-icons.right arrow_drop_down
            = link_to 'Refresh', '', class: 'btn green'
        %br
        %ul.collection
          - if @items.empty?
            %li.collection-item Sorry, nothing found :(
          - else
            = render partial: 'preview', collection: @items, cached: true

.fixed-action-btn
  %a#back-to-top.btn-floating.btn-large.red.scale-transition
    %i.large.material-icons keyboard_arrow_up

app/views/home/sitemap.xml.haml
!!! XML
%urlset{:xmlns => "http://www.sitemaps.org/schemas/sitemap/0.9"}
  - for item in Item.all
    %url
      %loc= item_url(item, protocol: 'https')
      %lastmod= item.updated_at.strftime('%Y-%m-%d')
      %changefreq hourly
      %priority 0.7
  %url
    %loc= root_url protocol: 'https'
    %priority 1
  %url
    %loc= most_traded_url protocol: 'https'
  %url
    %loc= top_flips_url protocol: 'https'
  %url
    %loc= zulrah_url protocol: 'https'